//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/ErrorHub.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiErrorHub")
#ifdef RESTRICT_NetGlobulusSimiErrorHub
#define INCLUDE_ALL_NetGlobulusSimiErrorHub 0
#else
#define INCLUDE_ALL_NetGlobulusSimiErrorHub 1
#endif
#undef RESTRICT_NetGlobulusSimiErrorHub

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SMErrorHub_) && (INCLUDE_ALL_NetGlobulusSimiErrorHub || defined(INCLUDE_SMErrorHub))
#define SMErrorHub_

@class SMRuntimeError;
@class SMToken;
@protocol SMErrorWatcher;

@interface SMErrorHub : NSObject

#pragma mark Package-Private

- (void)addWatcherWithSMErrorWatcher:(id<SMErrorWatcher>)watcher;

- (void)errorWithInt:(jint)line
        withNSString:(NSString *)message;

- (void)errorWithSMToken:(SMToken *)token
            withNSString:(NSString *)message;

- (void)removeWatcherWithSMErrorWatcher:(id<SMErrorWatcher>)watcher;

- (void)reportWithInt:(jint)line
         withNSString:(NSString *)where
         withNSString:(NSString *)message;

- (void)runtimeErrorWithSMRuntimeError:(SMRuntimeError *)error;

+ (SMErrorHub *)sharedInstance;

@end

J2OBJC_STATIC_INIT(SMErrorHub)

FOUNDATION_EXPORT SMErrorHub *SMErrorHub_sharedInstance(void);

J2OBJC_TYPE_LITERAL_HEADER(SMErrorHub)

@compatibility_alias NetGlobulusSimiErrorHub SMErrorHub;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiErrorHub")
