//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/Return.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiReturn")
#ifdef RESTRICT_NetGlobulusSimiReturn
#define INCLUDE_ALL_NetGlobulusSimiReturn 0
#else
#define INCLUDE_ALL_NetGlobulusSimiReturn 1
#endif
#undef RESTRICT_NetGlobulusSimiReturn

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SMReturn_) && (INCLUDE_ALL_NetGlobulusSimiReturn || defined(INCLUDE_SMReturn))
#define SMReturn_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;
@protocol SMSimiProperty;

@interface SMReturn : JavaLangRuntimeException {
 @public
  id<SMSimiProperty> prop_;
}

#pragma mark Package-Private

- (instancetype __nonnull)initWithSMSimiProperty:(id<SMSimiProperty>)prop;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1
                               withBoolean:(jboolean)arg2
                               withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SMReturn)

J2OBJC_FIELD_SETTER(SMReturn, prop_, id<SMSimiProperty>)

FOUNDATION_EXPORT void SMReturn_initWithSMSimiProperty_(SMReturn *self, id<SMSimiProperty> prop);

FOUNDATION_EXPORT SMReturn *new_SMReturn_initWithSMSimiProperty_(id<SMSimiProperty> prop) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SMReturn *create_SMReturn_initWithSMSimiProperty_(id<SMSimiProperty> prop);

J2OBJC_TYPE_LITERAL_HEADER(SMReturn)

@compatibility_alias NetGlobulusSimiReturn SMReturn;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiReturn")
