//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/BlockImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiBlockImpl")
#ifdef RESTRICT_NetGlobulusSimiBlockImpl
#define INCLUDE_ALL_NetGlobulusSimiBlockImpl 0
#else
#define INCLUDE_ALL_NetGlobulusSimiBlockImpl 1
#endif
#undef RESTRICT_NetGlobulusSimiBlockImpl

#if !defined (NetGlobulusSimiBlockImpl_) && (INCLUDE_ALL_NetGlobulusSimiBlockImpl || defined(INCLUDE_NetGlobulusSimiBlockImpl))
#define NetGlobulusSimiBlockImpl_

#define RESTRICT_NetGlobulusSimiSimiBlock 1
#define INCLUDE_NetGlobulusSimiSimiBlock 1
#include "SimiBlock.h"

#define RESTRICT_NetGlobulusSimiSimiCallable 1
#define INCLUDE_NetGlobulusSimiSimiCallable 1
#include "SimiCallable.h"

@class NetGlobulusSimiEnvironment;
@class NetGlobulusSimiExpr_Block;
@class NetGlobulusSimiSimiObjectImpl;
@protocol JavaUtilList;
@protocol NetGlobulusSimiBlockInterpreter;
@protocol NetGlobulusSimiSimiProperty;

@interface NetGlobulusSimiBlockImpl : NSObject < NetGlobulusSimiSimiBlock, NetGlobulusSimiSimiCallable > {
 @public
  NetGlobulusSimiExpr_Block *declaration_;
  NetGlobulusSimiEnvironment *closure_;
}

#pragma mark Public

- (jint)arity;

- (id<NetGlobulusSimiSimiProperty>)callWithNetGlobulusSimiBlockInterpreter:(id<NetGlobulusSimiBlockInterpreter>)interpreter
                                                          withJavaUtilList:(id<JavaUtilList>)arguments
                                                               withBoolean:(jboolean)rethrow;

- (id<JavaUtilList>)getStatements;

- (NSString *)description;

- (void)yieldWithInt:(jint)index;

#pragma mark Package-Private

- (instancetype)initWithNetGlobulusSimiExpr_Block:(NetGlobulusSimiExpr_Block *)declaration
                   withNetGlobulusSimiEnvironment:(NetGlobulusSimiEnvironment *)closure;

- (NetGlobulusSimiBlockImpl *)bindWithNetGlobulusSimiSimiObjectImpl:(NetGlobulusSimiSimiObjectImpl *)instance;

- (jboolean)isNative;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiBlockImpl)

J2OBJC_FIELD_SETTER(NetGlobulusSimiBlockImpl, declaration_, NetGlobulusSimiExpr_Block *)
J2OBJC_FIELD_SETTER(NetGlobulusSimiBlockImpl, closure_, NetGlobulusSimiEnvironment *)

FOUNDATION_EXPORT void NetGlobulusSimiBlockImpl_initWithNetGlobulusSimiExpr_Block_withNetGlobulusSimiEnvironment_(NetGlobulusSimiBlockImpl *self, NetGlobulusSimiExpr_Block *declaration, NetGlobulusSimiEnvironment *closure);

FOUNDATION_EXPORT NetGlobulusSimiBlockImpl *new_NetGlobulusSimiBlockImpl_initWithNetGlobulusSimiExpr_Block_withNetGlobulusSimiEnvironment_(NetGlobulusSimiExpr_Block *declaration, NetGlobulusSimiEnvironment *closure) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiBlockImpl *create_NetGlobulusSimiBlockImpl_initWithNetGlobulusSimiExpr_Block_withNetGlobulusSimiEnvironment_(NetGlobulusSimiExpr_Block *declaration, NetGlobulusSimiEnvironment *closure);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiBlockImpl)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiBlockImpl")
