//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/Break.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiBreak")
#ifdef RESTRICT_NetGlobulusSimiBreak
#define INCLUDE_ALL_NetGlobulusSimiBreak 0
#else
#define INCLUDE_ALL_NetGlobulusSimiBreak 1
#endif
#undef RESTRICT_NetGlobulusSimiBreak

#if !defined (NetGlobulusSimiBreak_) && (INCLUDE_ALL_NetGlobulusSimiBreak || defined(INCLUDE_NetGlobulusSimiBreak))
#define NetGlobulusSimiBreak_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface NetGlobulusSimiBreak : JavaLangRuntimeException

#pragma mark Package-Private

- (instancetype)init;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiBreak)

FOUNDATION_EXPORT void NetGlobulusSimiBreak_init(NetGlobulusSimiBreak *self);

FOUNDATION_EXPORT NetGlobulusSimiBreak *new_NetGlobulusSimiBreak_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiBreak *create_NetGlobulusSimiBreak_init(void);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiBreak)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiBreak")
