//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/Pass.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiPass")
#ifdef RESTRICT_NetGlobulusSimiPass
#define INCLUDE_ALL_NetGlobulusSimiPass 0
#else
#define INCLUDE_ALL_NetGlobulusSimiPass 1
#endif
#undef RESTRICT_NetGlobulusSimiPass

#if !defined (NetGlobulusSimiPass_) && (INCLUDE_ALL_NetGlobulusSimiPass || defined(INCLUDE_NetGlobulusSimiPass))
#define NetGlobulusSimiPass_

#define RESTRICT_NetGlobulusSimiSimiValue 1
#define INCLUDE_NetGlobulusSimiSimiValue 1
#include "SimiValue.h"

@interface NetGlobulusSimiPass : NetGlobulusSimiSimiValue

#pragma mark Public

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiPass)

FOUNDATION_EXPORT void NetGlobulusSimiPass_init(NetGlobulusSimiPass *self);

FOUNDATION_EXPORT NetGlobulusSimiPass *new_NetGlobulusSimiPass_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiPass *create_NetGlobulusSimiPass_init(void);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiPass)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiPass")
