//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/SimiFunction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiSimiFunction")
#ifdef RESTRICT_NetGlobulusSimiSimiFunction
#define INCLUDE_ALL_NetGlobulusSimiSimiFunction 0
#else
#define INCLUDE_ALL_NetGlobulusSimiSimiFunction 1
#endif
#undef RESTRICT_NetGlobulusSimiSimiFunction

#if !defined (NetGlobulusSimiSimiFunction_) && (INCLUDE_ALL_NetGlobulusSimiSimiFunction || defined(INCLUDE_NetGlobulusSimiSimiFunction))
#define NetGlobulusSimiSimiFunction_

#define RESTRICT_NetGlobulusSimiSimiCallable 1
#define INCLUDE_NetGlobulusSimiSimiCallable 1
#include "SimiCallable.h"

@class NetGlobulusSimiEnvironment;
@class NetGlobulusSimiSimiObjectImpl;
@class NetGlobulusSimiStmt_Function;
@protocol JavaUtilList;
@protocol NetGlobulusSimiBlockInterpreter;
@protocol NetGlobulusSimiSimiProperty;

@interface NetGlobulusSimiSimiFunction : NSObject < NetGlobulusSimiSimiCallable > {
 @public
  NetGlobulusSimiStmt_Function *declaration_;
  jboolean isNative_;
  id<JavaUtilList> annotations_;
}

#pragma mark Public

- (jint)arity;

- (id<NetGlobulusSimiSimiProperty>)callWithNetGlobulusSimiBlockInterpreter:(id<NetGlobulusSimiBlockInterpreter>)interpreter
                                                          withJavaUtilList:(id<JavaUtilList>)arguments
                                                               withBoolean:(jboolean)rethrow;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithNetGlobulusSimiStmt_Function:(NetGlobulusSimiStmt_Function *)declaration
                      withNetGlobulusSimiEnvironment:(NetGlobulusSimiEnvironment *)closure
                                         withBoolean:(jboolean)isInitializer
                                         withBoolean:(jboolean)isNative
                                    withJavaUtilList:(id<JavaUtilList>)annotations;

- (NetGlobulusSimiSimiFunction *)bindWithNetGlobulusSimiSimiObjectImpl:(NetGlobulusSimiSimiObjectImpl *)instance;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiFunction)

J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiFunction, declaration_, NetGlobulusSimiStmt_Function *)
J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiFunction, annotations_, id<JavaUtilList>)

FOUNDATION_EXPORT void NetGlobulusSimiSimiFunction_initWithNetGlobulusSimiStmt_Function_withNetGlobulusSimiEnvironment_withBoolean_withBoolean_withJavaUtilList_(NetGlobulusSimiSimiFunction *self, NetGlobulusSimiStmt_Function *declaration, NetGlobulusSimiEnvironment *closure, jboolean isInitializer, jboolean isNative, id<JavaUtilList> annotations);

FOUNDATION_EXPORT NetGlobulusSimiSimiFunction *new_NetGlobulusSimiSimiFunction_initWithNetGlobulusSimiStmt_Function_withNetGlobulusSimiEnvironment_withBoolean_withBoolean_withJavaUtilList_(NetGlobulusSimiStmt_Function *declaration, NetGlobulusSimiEnvironment *closure, jboolean isInitializer, jboolean isNative, id<JavaUtilList> annotations) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiFunction *create_NetGlobulusSimiSimiFunction_initWithNetGlobulusSimiStmt_Function_withNetGlobulusSimiEnvironment_withBoolean_withBoolean_withJavaUtilList_(NetGlobulusSimiStmt_Function *declaration, NetGlobulusSimiEnvironment *closure, jboolean isInitializer, jboolean isNative, id<JavaUtilList> annotations);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiFunction)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiSimiFunction")
