//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/SimiNativeObject.java
//

#include "J2ObjC_source.h"
#include "java/util/LinkedHashMap.h"
#include "SimiNativeObject.h"
#include "SimiObjectImpl.h"

@implementation SMSimiNativeObject

- (instancetype __nonnull)initWithJavaUtilLinkedHashMap:(JavaUtilLinkedHashMap *)props {
  SMSimiNativeObject_initWithJavaUtilLinkedHashMap_(self, props);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithJavaUtilLinkedHashMap:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LJavaUtilLinkedHashMap;", "(Ljava/util/LinkedHashMap<Ljava/lang/String;LSimiProperty;>;)V" };
  static const J2ObjcClassInfo _SMSimiNativeObject = { "SimiNativeObject", "net.globulus.simi", ptrTable, methods, NULL, 7, 0x0, 1, 0, -1, -1, -1, -1, -1 };
  return &_SMSimiNativeObject;
}

@end

void SMSimiNativeObject_initWithJavaUtilLinkedHashMap_(SMSimiNativeObject *self, JavaUtilLinkedHashMap *props) {
  SMSimiObjectImpl_Dictionary_initWithSMSimiClassImpl_withBoolean_withJavaUtilLinkedHashMap_(self, nil, true, props);
}

SMSimiNativeObject *new_SMSimiNativeObject_initWithJavaUtilLinkedHashMap_(JavaUtilLinkedHashMap *props) {
  J2OBJC_NEW_IMPL(SMSimiNativeObject, initWithJavaUtilLinkedHashMap_, props)
}

SMSimiNativeObject *create_SMSimiNativeObject_initWithJavaUtilLinkedHashMap_(JavaUtilLinkedHashMap *props) {
  J2OBJC_CREATE_IMPL(SMSimiNativeObject, initWithJavaUtilLinkedHashMap_, props)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SMSimiNativeObject)
