//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/SimiMapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiSimiMapper")
#ifdef RESTRICT_NetGlobulusSimiSimiMapper
#define INCLUDE_ALL_NetGlobulusSimiSimiMapper 0
#else
#define INCLUDE_ALL_NetGlobulusSimiSimiMapper 1
#endif
#undef RESTRICT_NetGlobulusSimiSimiMapper

#if !defined (NetGlobulusSimiSimiMapper_) && (INCLUDE_ALL_NetGlobulusSimiSimiMapper || defined(INCLUDE_NetGlobulusSimiSimiMapper))
#define NetGlobulusSimiSimiMapper_

@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol NetGlobulusSimiSimiObject;
@protocol NetGlobulusSimiSimiProperty;

@interface NetGlobulusSimiSimiMapper : NSObject

#pragma mark Public

+ (id<JavaUtilMap>)fromObjectWithNetGlobulusSimiSimiObject:(id<NetGlobulusSimiSimiObject>)object;

+ (id<NetGlobulusSimiSimiObject>)toObjectWithJavaUtilList:(id<JavaUtilList>)list
                                              withBoolean:(jboolean)immutable;

+ (id<NetGlobulusSimiSimiObject>)toObjectWithJavaUtilMap:(id<JavaUtilMap>)map
                                             withBoolean:(jboolean)immutable;

+ (id<NetGlobulusSimiSimiProperty>)toSimiPropertyWithId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiMapper)

FOUNDATION_EXPORT id<NetGlobulusSimiSimiObject> NetGlobulusSimiSimiMapper_toObjectWithJavaUtilMap_withBoolean_(id<JavaUtilMap> map, jboolean immutable);

FOUNDATION_EXPORT id<NetGlobulusSimiSimiObject> NetGlobulusSimiSimiMapper_toObjectWithJavaUtilList_withBoolean_(id<JavaUtilList> list, jboolean immutable);

FOUNDATION_EXPORT id<JavaUtilMap> NetGlobulusSimiSimiMapper_fromObjectWithNetGlobulusSimiSimiObject_(id<NetGlobulusSimiSimiObject> object);

FOUNDATION_EXPORT id<NetGlobulusSimiSimiProperty> NetGlobulusSimiSimiMapper_toSimiPropertyWithId_(id value);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiMapper)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiSimiMapper")
