//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/SimiClassImpl.java
//

#include "J2ObjC_source.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Integer.h"
#include "java/lang/Math.h"
#include "java/lang/StringBuilder.h"
#include "java/util/ArrayList.h"
#include "java/util/Comparator.h"
#include "java/util/HashMap.h"
#include "java/util/HashSet.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/Optional.h"
#include "java/util/Set.h"
#include "java/util/function/BiFunction.h"
#include "java/util/function/BinaryOperator.h"
#include "java/util/function/Function.h"
#include "java/util/function/Predicate.h"
#include "java/util/function/Supplier.h"
#include "java/util/function/ToIntFunction.h"
#include "java/util/stream/Collector.h"
#include "java/util/stream/Collectors.h"
#include "java/util/stream/Stream.h"
#include "BlockInterpreter.h"
#include "Constants.h"
#include "Environment.h"
#include "Interpreter.h"
#include "NativeModulesManager.h"
#include "OverloadableFunction.h"
#include "SimiClassImpl.h"
#include "SimiFunction.h"
#include "SimiMethod.h"
#include "SimiObject.h"
#include "SimiObjectImpl.h"
#include "SimiProperty.h"
#include "SimiPropertyImpl.h"
#include "SimiValue.h"
#include "Token.h"

#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface NetGlobulusSimiSimiClassImpl () {
 @public
  id<JavaUtilMap> methods_;
}

- (instancetype)initWithNSString:(NSString *)name;

- (NetGlobulusSimiSimiMethod *)findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl:(NetGlobulusSimiSimiObjectImpl *)instance
                                                                           withNSString:(NSString *)name
                                                                                withInt:(jint)arity;

@end

J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiClassImpl, methods_, id<JavaUtilMap>)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_initWithNSString_(NetGlobulusSimiSimiClassImpl *self, NSString *name);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl *new_NetGlobulusSimiSimiClassImpl_initWithNSString_(NSString *name) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl *create_NetGlobulusSimiSimiClassImpl_initWithNSString_(NSString *name);

__attribute__((unused)) static NetGlobulusSimiSimiMethod *NetGlobulusSimiSimiClassImpl_findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl_withNSString_withInt_(NetGlobulusSimiSimiClassImpl *self, NetGlobulusSimiSimiObjectImpl *instance, NSString *name, jint arity);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$1 : NSObject < JavaUtilFunctionPredicate > {
 @public
  NSString *val$name_;
}

- (jboolean)testWithId:(id<JavaUtilMap_Entry>)e;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$1)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(NetGlobulusSimiSimiClassImpl_$Lambda$1 *self, NSString *capture$0);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$1 *new_NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(NSString *capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$1 *create_NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(NSString *capture$0);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$2 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(id<JavaUtilMap_Entry>)a;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$2)

inline NetGlobulusSimiSimiClassImpl_$Lambda$2 *NetGlobulusSimiSimiClassImpl_$Lambda$2_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$2 *NetGlobulusSimiSimiClassImpl_$Lambda$2_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$2, instance, NetGlobulusSimiSimiClassImpl_$Lambda$2 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$2_init(NetGlobulusSimiSimiClassImpl_$Lambda$2 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$2 *new_NetGlobulusSimiSimiClassImpl_$Lambda$2_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$2 *create_NetGlobulusSimiSimiClassImpl_$Lambda$2_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$3 : NSObject < JavaUtilFunctionPredicate > {
 @public
  NSString *val$name_;
  jint val$arity_;
}

- (jboolean)testWithId:(id<JavaUtilMap_Entry>)e;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$3)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(NetGlobulusSimiSimiClassImpl_$Lambda$3 *self, NSString *capture$0, jint capture$1);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$3 *new_NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(NSString *capture$0, jint capture$1) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$3 *create_NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(NSString *capture$0, jint capture$1);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$4 : NSObject < JavaUtilFunctionToIntFunction > {
 @public
  jint val$arity_;
}

- (jint)applyAsIntWithId:(id<JavaUtilMap_Entry>)l;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$4)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(NetGlobulusSimiSimiClassImpl_$Lambda$4 *self, jint capture$0);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$4 *new_NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(jint capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$4 *create_NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(jint capture$0);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$5 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(id<JavaUtilMap_Entry>)a;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$5)

inline NetGlobulusSimiSimiClassImpl_$Lambda$5 *NetGlobulusSimiSimiClassImpl_$Lambda$5_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$5 *NetGlobulusSimiSimiClassImpl_$Lambda$5_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$5, instance, NetGlobulusSimiSimiClassImpl_$Lambda$5 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$5_init(NetGlobulusSimiSimiClassImpl_$Lambda$5 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$5 *new_NetGlobulusSimiSimiClassImpl_$Lambda$5_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$5 *create_NetGlobulusSimiSimiClassImpl_$Lambda$5_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$6 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(NetGlobulusSimiSimiClassImpl *)c;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$6)

inline NetGlobulusSimiSimiClassImpl_$Lambda$6 *NetGlobulusSimiSimiClassImpl_$Lambda$6_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$6 *NetGlobulusSimiSimiClassImpl_$Lambda$6_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$6, instance, NetGlobulusSimiSimiClassImpl_$Lambda$6 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$6_init(NetGlobulusSimiSimiClassImpl_$Lambda$6 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$6 *new_NetGlobulusSimiSimiClassImpl_$Lambda$6_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$6 *create_NetGlobulusSimiSimiClassImpl_$Lambda$6_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$7 : NSObject < JavaUtilFunctionBinaryOperator >

- (id)applyWithId:(NSString *)l
           withId:(NSString *)r;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$7)

inline NetGlobulusSimiSimiClassImpl_$Lambda$7 *NetGlobulusSimiSimiClassImpl_$Lambda$7_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$7 *NetGlobulusSimiSimiClassImpl_$Lambda$7_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$7, instance, NetGlobulusSimiSimiClassImpl_$Lambda$7 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$7_init(NetGlobulusSimiSimiClassImpl_$Lambda$7 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$7 *new_NetGlobulusSimiSimiClassImpl_$Lambda$7_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$7 *create_NetGlobulusSimiSimiClassImpl_$Lambda$7_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$8 : NSObject < JavaUtilFunctionPredicate >

- (jboolean)testWithId:(id<JavaUtilMap_Entry>)e;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$8)

inline NetGlobulusSimiSimiClassImpl_$Lambda$8 *NetGlobulusSimiSimiClassImpl_$Lambda$8_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$8 *NetGlobulusSimiSimiClassImpl_$Lambda$8_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$8, instance, NetGlobulusSimiSimiClassImpl_$Lambda$8 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$8_init(NetGlobulusSimiSimiClassImpl_$Lambda$8 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$8 *new_NetGlobulusSimiSimiClassImpl_$Lambda$8_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$8 *create_NetGlobulusSimiSimiClassImpl_$Lambda$8_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$9 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(id<JavaUtilMap_Entry>)a;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$9)

inline NetGlobulusSimiSimiClassImpl_$Lambda$9 *NetGlobulusSimiSimiClassImpl_$Lambda$9_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$9 *NetGlobulusSimiSimiClassImpl_$Lambda$9_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$9, instance, NetGlobulusSimiSimiClassImpl_$Lambda$9 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$9_init(NetGlobulusSimiSimiClassImpl_$Lambda$9 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$9 *new_NetGlobulusSimiSimiClassImpl_$Lambda$9_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$9 *create_NetGlobulusSimiSimiClassImpl_$Lambda$9_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$10 : NSObject < JavaUtilFunctionFunction >

- (id)applyWithId:(NSString *)a;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$10)

inline NetGlobulusSimiSimiClassImpl_$Lambda$10 *NetGlobulusSimiSimiClassImpl_$Lambda$10_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$10 *NetGlobulusSimiSimiClassImpl_$Lambda$10_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$10, instance, NetGlobulusSimiSimiClassImpl_$Lambda$10 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$10_init(NetGlobulusSimiSimiClassImpl_$Lambda$10 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$10 *new_NetGlobulusSimiSimiClassImpl_$Lambda$10_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$10 *create_NetGlobulusSimiSimiClassImpl_$Lambda$10_init(void);

@interface NetGlobulusSimiSimiClassImpl_$Lambda$11 : NSObject < JavaUtilFunctionSupplier >

- (id)get;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiClassImpl_$Lambda$11)

inline NetGlobulusSimiSimiClassImpl_$Lambda$11 *NetGlobulusSimiSimiClassImpl_$Lambda$11_get_instance(void);
static NetGlobulusSimiSimiClassImpl_$Lambda$11 *NetGlobulusSimiSimiClassImpl_$Lambda$11_instance;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiClassImpl_$Lambda$11, instance, NetGlobulusSimiSimiClassImpl_$Lambda$11 *)

__attribute__((unused)) static void NetGlobulusSimiSimiClassImpl_$Lambda$11_init(NetGlobulusSimiSimiClassImpl_$Lambda$11 *self);

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$11 *new_NetGlobulusSimiSimiClassImpl_$Lambda$11_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiSimiClassImpl_$Lambda$11 *create_NetGlobulusSimiSimiClassImpl_$Lambda$11_init(void);

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl)

NetGlobulusSimiSimiClassImpl *NetGlobulusSimiSimiClassImpl_CLASS;

@implementation NetGlobulusSimiSimiClassImpl

- (instancetype)initWithNSString:(NSString *)name {
  NetGlobulusSimiSimiClassImpl_initWithNSString_(self, name);
  return self;
}

- (instancetype)initWithNSString:(NSString *)name
                withJavaUtilList:(id<JavaUtilList>)superclasses
                 withJavaUtilMap:(id<JavaUtilMap>)constants
                 withJavaUtilMap:(id<JavaUtilMap>)methods {
  NetGlobulusSimiSimiClassImpl_initWithNSString_withJavaUtilList_withJavaUtilMap_withJavaUtilMap_(self, name, superclasses, constants, methods);
  return self;
}

- (id<NetGlobulusSimiSimiProperty>)getWithNetGlobulusSimiToken:(NetGlobulusSimiToken *)name
                                           withJavaLangInteger:(JavaLangInteger *)arity
                                withNetGlobulusSimiEnvironment:(NetGlobulusSimiEnvironment *)environment {
  id<NetGlobulusSimiSimiProperty> prop = [super getWithNetGlobulusSimiToken:name withJavaLangInteger:arity withNetGlobulusSimiEnvironment:environment];
  if (prop != nil) {
    return prop;
  }
  NetGlobulusSimiSimiMethod *method = [self findMethodWithNetGlobulusSimiSimiObjectImpl:nil withNSString:((NetGlobulusSimiToken *) nil_chk(name))->lexeme_ withJavaLangInteger:arity];
  if (method != nil) {
    return new_NetGlobulusSimiSimiPropertyImpl_initWithNetGlobulusSimiSimiValue_withJavaUtilList_(new_NetGlobulusSimiSimiValue_Callable_initWithNetGlobulusSimiSimiCallable_withNSString_withNetGlobulusSimiSimiObject_(method, name->lexeme_, self), ((NetGlobulusSimiSimiFunction *) nil_chk(method->function_))->annotations_);
  }
  if (superclasses_ != nil) {
    for (NetGlobulusSimiSimiClassImpl * __strong superclass_ in superclasses_) {
      id<NetGlobulusSimiSimiProperty> superclassProp = [((NetGlobulusSimiSimiClassImpl *) nil_chk(superclass_)) getWithNetGlobulusSimiToken:name withJavaLangInteger:arity withNetGlobulusSimiEnvironment:environment];
      if (superclassProp != nil) {
        return superclassProp;
      }
    }
  }
  return nil;
}

- (NetGlobulusSimiSimiMethod *)findMethodWithNetGlobulusSimiSimiObjectImpl:(NetGlobulusSimiSimiObjectImpl *)instance
                                                              withNSString:(NSString *)name
                                                       withJavaLangInteger:(JavaLangInteger *)arity {
  NetGlobulusSimiSimiObjectImpl *binder = (instance != nil) ? instance : self;
  if (arity == nil) {
    JavaUtilOptional *candidate = [((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilSet>) nil_chk([((id<JavaUtilMap>) nil_chk(methods_)) entrySet])) stream])) filterWithJavaUtilFunctionPredicate:new_NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(name)])) mapWithJavaUtilFunctionFunction:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$2, instance)])) findFirst];
    if ([((JavaUtilOptional *) nil_chk(candidate)) isPresent]) {
      return new_NetGlobulusSimiSimiMethod_initWithNetGlobulusSimiSimiClassImpl_withNetGlobulusSimiSimiFunction_(self, [candidate get]);
    }
  }
  else {
    NetGlobulusSimiOverloadableFunction *of = new_NetGlobulusSimiOverloadableFunction_initWithNSString_withInt_(name, [arity intValue]);
    if ([((id<JavaUtilMap>) nil_chk(methods_)) containsKeyWithId:of]) {
      return new_NetGlobulusSimiSimiMethod_initWithNetGlobulusSimiSimiClassImpl_withNetGlobulusSimiSimiFunction_(self, [((NetGlobulusSimiSimiFunction *) nil_chk([methods_ getWithId:of])) bindWithNetGlobulusSimiSimiObjectImpl:binder]);
    }
  }
  if (superclasses_ != nil) {
    for (NetGlobulusSimiSimiClassImpl * __strong superclass_ in superclasses_) {
      NetGlobulusSimiSimiMethod *method = [((NetGlobulusSimiSimiClassImpl *) nil_chk(superclass_)) findMethodWithNetGlobulusSimiSimiObjectImpl:instance withNSString:name withJavaLangInteger:arity];
      if (method != nil) {
        return method;
      }
    }
  }
  if (arity == nil) {
    return nil;
  }
  else {
    return NetGlobulusSimiSimiClassImpl_findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl_withNSString_withInt_(self, instance, name, [arity intValue]);
  }
}

- (NetGlobulusSimiSimiMethod *)findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl:(NetGlobulusSimiSimiObjectImpl *)instance
                                                                           withNSString:(NSString *)name
                                                                                withInt:(jint)arity {
  return NetGlobulusSimiSimiClassImpl_findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl_withNSString_withInt_(self, instance, name, arity);
}

- (id<NetGlobulusSimiSimiProperty>)init__WithNetGlobulusSimiBlockInterpreter:(id<NetGlobulusSimiBlockInterpreter>)interpreter
                                                            withJavaUtilList:(id<JavaUtilList>)arguments {
  NetGlobulusSimiSimiObjectImpl *instance = new_NetGlobulusSimiSimiObjectImpl_Dictionary_initWithNetGlobulusSimiSimiClassImpl_withBoolean_withJavaUtilLinkedHashMap_(self, true, new_JavaUtilLinkedHashMap_init());
  NetGlobulusSimiSimiMethod *initializer = [self findMethodWithNetGlobulusSimiSimiObjectImpl:instance withNSString:NetGlobulusSimiConstants_INIT withJavaLangInteger:JavaLangInteger_valueOfWithInt_([((id<JavaUtilList>) nil_chk(arguments)) size])];
  if (initializer == nil) {
    initializer = [self findMethodWithNetGlobulusSimiSimiObjectImpl:instance withNSString:JreStrcat("$$", NetGlobulusSimiConstants_PRIVATE, NetGlobulusSimiConstants_INIT) withJavaLangInteger:JavaLangInteger_valueOfWithInt_([arguments size])];
  }
  if (initializer != nil) {
    if (((NetGlobulusSimiSimiFunction *) nil_chk(initializer->function_))->isNative_) {
      NetGlobulusSimiInterpreter *in = (NetGlobulusSimiInterpreter *) cast_chk(interpreter, [NetGlobulusSimiInterpreter class]);
      instance = (NetGlobulusSimiSimiObjectImpl *) cast_chk([((NetGlobulusSimiSimiValue *) nil_chk([((id<NetGlobulusSimiSimiProperty>) nil_chk([((NetGlobulusSimiNativeModulesManager *) nil_chk(((NetGlobulusSimiInterpreter *) nil_chk(in))->nativeModulesManager_)) callWithNSString:name_ withNSString:NetGlobulusSimiConstants_INIT withNetGlobulusSimiSimiObject:self withNetGlobulusSimiInterpreter:in withJavaUtilList:arguments])) getValue])) getObject], [NetGlobulusSimiSimiObjectImpl class]);
    }
    else {
      (void) [initializer->function_ callWithNetGlobulusSimiBlockInterpreter:interpreter withJavaUtilList:arguments withBoolean:false];
    }
  }
  return new_NetGlobulusSimiSimiValue_Object_initWithNetGlobulusSimiSimiObject_(instance);
}

- (NSString *)description {
  JavaLangStringBuilder *sb = new_JavaLangStringBuilder_init();
  (void) [sb appendWithNSString:name_];
  if (superclasses_ != nil) {
    (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@"("])) appendWithNSString:[((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([superclasses_ stream])) mapWithJavaUtilFunctionFunction:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$6, instance)])) reduceWithId:@"" withJavaUtilFunctionBinaryOperator:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$7, instance)]])) appendWithNSString:@")"];
  }
  (void) [sb appendWithNSString:@" = [\n"];
  for (NetGlobulusSimiOverloadableFunction * __strong key in nil_chk([((id<JavaUtilMap>) nil_chk(methods_)) keySet])) {
    (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@"\t"])) appendWithNSString:((NetGlobulusSimiOverloadableFunction *) nil_chk(key))->name_])) appendWithNSString:@"("])) appendWithInt:key->arity_])) appendWithNSString:@")"])) appendWithNSString:@" = "])) appendWithId:[methods_ getWithId:key]])) appendWithNSString:@"\n"];
  }
  (void) [sb appendWithNSString:[self printFields]];
  (void) [sb appendWithNSString:@"]"];
  return [sb description];
}

- (id<JavaUtilSet>)getConstructors {
  id<JavaUtilSet> constructors = [((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilSet>) nil_chk([((id<JavaUtilMap>) nil_chk(methods_)) entrySet])) stream])) filterWithJavaUtilFunctionPredicate:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$8, instance)])) mapWithJavaUtilFunctionFunction:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$9, instance)])) collectWithJavaUtilStreamCollector:JavaUtilStreamCollectors_toSet()];
  if (superclasses_ != nil) {
    for (NetGlobulusSimiSimiClassImpl * __strong superclass_ in superclasses_) {
      [((id<JavaUtilSet>) nil_chk(constructors)) addAllWithJavaUtilCollection:[((NetGlobulusSimiSimiClassImpl *) nil_chk(superclass_)) getConstructors]];
    }
  }
  return constructors;
}

- (id<JavaUtilSet>)allKeys {
  id<JavaUtilSet> keys = new_JavaUtilHashSet_initWithJavaUtilCollection_([((JavaUtilLinkedHashMap *) nil_chk(fields_)) keySet]);
  if (superclasses_ != nil) {
    for (NetGlobulusSimiSimiClassImpl * __strong superclass_ in superclasses_) {
      [keys addAllWithJavaUtilCollection:[((NetGlobulusSimiSimiClassImpl *) nil_chk(superclass_)) allKeys]];
    }
  }
  return keys;
}

- (JavaUtilArrayList *)keys {
  return [((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilSet>) nil_chk([self allKeys])) stream])) mapWithJavaUtilFunctionFunction:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$10, instance)])) collectWithJavaUtilStreamCollector:JavaUtilStreamCollectors_toCollectionWithJavaUtilFunctionSupplier_(JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$11, instance))];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 1, -1, 2, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiProperty;", 0x0, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiMethod;", 0x0, 5, 6, -1, -1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiMethod;", 0x2, 7, 8, -1, -1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiProperty;", 0x1, 9, 10, -1, 11, -1, -1 },
    { NULL, "LNSString;", 0x1, 12, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x0, -1, -1, -1, 13, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x0, -1, -1, -1, 14, -1, -1 },
    { NULL, "LJavaUtilArrayList;", 0x1, -1, -1, -1, 15, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithNSString:withJavaUtilList:withJavaUtilMap:withJavaUtilMap:);
  methods[2].selector = @selector(getWithNetGlobulusSimiToken:withJavaLangInteger:withNetGlobulusSimiEnvironment:);
  methods[3].selector = @selector(findMethodWithNetGlobulusSimiSimiObjectImpl:withNSString:withJavaLangInteger:);
  methods[4].selector = @selector(findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl:withNSString:withInt:);
  methods[5].selector = @selector(init__WithNetGlobulusSimiBlockInterpreter:withJavaUtilList:);
  methods[6].selector = @selector(description);
  methods[7].selector = @selector(getConstructors);
  methods[8].selector = @selector(allKeys);
  methods[9].selector = @selector(keys);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "superclasses_", "LJavaUtilList;", .constantValue.asLong = 0, 0x10, -1, -1, 16, -1 },
    { "methods_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x12, -1, -1, 17, -1 },
    { "CLASS", "LNetGlobulusSimiSimiClassImpl;", .constantValue.asLong = 0, 0x18, -1, 18, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LNSString;LJavaUtilList;LJavaUtilMap;LJavaUtilMap;", "(Ljava/lang/String;Ljava/util/List<LSimiClassImpl;>;Ljava/util/Map<Ljava/lang/String;LSimiProperty;>;Ljava/util/Map<LOverloadableFunction;LSimiFunction;>;)V", "get", "LNetGlobulusSimiToken;LJavaLangInteger;LNetGlobulusSimiEnvironment;", "findMethod", "LNetGlobulusSimiSimiObjectImpl;LNSString;LJavaLangInteger;", "findClosestVarargMethod", "LNetGlobulusSimiSimiObjectImpl;LNSString;I", "init", "LNetGlobulusSimiBlockInterpreter;LJavaUtilList;", "(LBlockInterpreter;Ljava/util/List<LSimiProperty;>;)LSimiProperty;", "toString", "()Ljava/util/Set<LSimiFunction;>;", "()Ljava/util/Set<Ljava/lang/String;>;", "()Ljava/util/ArrayList<LSimiValue;>;", "Ljava/util/List<LSimiClassImpl;>;", "Ljava/util/Map<LOverloadableFunction;LSimiFunction;>;", &NetGlobulusSimiSimiClassImpl_CLASS, "LNetGlobulusSimiSimiClassImpl_SuperClassesList;" };
  static const J2ObjcClassInfo _NetGlobulusSimiSimiClassImpl = { "SimiClassImpl", "net.globulus.simi", ptrTable, methods, fields, 7, 0x0, 10, 4, -1, 19, -1, -1, -1 };
  return &_NetGlobulusSimiSimiClassImpl;
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl class]) {
    NetGlobulusSimiSimiClassImpl_CLASS = new_NetGlobulusSimiSimiClassImpl_initWithNSString_(NetGlobulusSimiConstants_CLASS_CLASS);
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_initWithNSString_(NetGlobulusSimiSimiClassImpl *self, NSString *name) {
  NetGlobulusSimiSimiObjectImpl_Dictionary_initWithNetGlobulusSimiSimiClassImpl_withBoolean_withJavaUtilLinkedHashMap_(self, nil, true, new_JavaUtilLinkedHashMap_init());
  self->name_ = name;
  self->superclasses_ = nil;
  self->methods_ = new_JavaUtilHashMap_init();
}

NetGlobulusSimiSimiClassImpl *new_NetGlobulusSimiSimiClassImpl_initWithNSString_(NSString *name) {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl, initWithNSString_, name)
}

NetGlobulusSimiSimiClassImpl *create_NetGlobulusSimiSimiClassImpl_initWithNSString_(NSString *name) {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl, initWithNSString_, name)
}

void NetGlobulusSimiSimiClassImpl_initWithNSString_withJavaUtilList_withJavaUtilMap_withJavaUtilMap_(NetGlobulusSimiSimiClassImpl *self, NSString *name, id<JavaUtilList> superclasses, id<JavaUtilMap> constants, id<JavaUtilMap> methods) {
  NetGlobulusSimiSimiObjectImpl_Dictionary_initWithNetGlobulusSimiSimiClassImpl_withBoolean_withJavaUtilLinkedHashMap_(self, NetGlobulusSimiSimiClassImpl_CLASS, ![((NSString *) nil_chk(name)) java_hasPrefix:NetGlobulusSimiConstants_MUTABLE], new_JavaUtilLinkedHashMap_initWithJavaUtilMap_(constants));
  self->superclasses_ = superclasses;
  self->name_ = name;
  self->methods_ = methods;
}

NetGlobulusSimiSimiClassImpl *new_NetGlobulusSimiSimiClassImpl_initWithNSString_withJavaUtilList_withJavaUtilMap_withJavaUtilMap_(NSString *name, id<JavaUtilList> superclasses, id<JavaUtilMap> constants, id<JavaUtilMap> methods) {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl, initWithNSString_withJavaUtilList_withJavaUtilMap_withJavaUtilMap_, name, superclasses, constants, methods)
}

NetGlobulusSimiSimiClassImpl *create_NetGlobulusSimiSimiClassImpl_initWithNSString_withJavaUtilList_withJavaUtilMap_withJavaUtilMap_(NSString *name, id<JavaUtilList> superclasses, id<JavaUtilMap> constants, id<JavaUtilMap> methods) {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl, initWithNSString_withJavaUtilList_withJavaUtilMap_withJavaUtilMap_, name, superclasses, constants, methods)
}

NetGlobulusSimiSimiMethod *NetGlobulusSimiSimiClassImpl_findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl_withNSString_withInt_(NetGlobulusSimiSimiClassImpl *self, NetGlobulusSimiSimiObjectImpl *instance, NSString *name, jint arity) {
  JavaUtilOptional *candidate = [((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilStreamStream>) nil_chk([((id<JavaUtilSet>) nil_chk([((id<JavaUtilMap>) nil_chk(self->methods_)) entrySet])) stream])) filterWithJavaUtilFunctionPredicate:new_NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(name, arity)])) sortedWithJavaUtilComparator:JavaUtilComparator_comparingIntWithJavaUtilFunctionToIntFunction_(new_NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(arity))])) mapWithJavaUtilFunctionFunction:JreLoadStatic(NetGlobulusSimiSimiClassImpl_$Lambda$5, instance)])) findFirst];
  if ([((JavaUtilOptional *) nil_chk(candidate)) isPresent]) {
    return new_NetGlobulusSimiSimiMethod_initWithNetGlobulusSimiSimiClassImpl_withNetGlobulusSimiSimiFunction_(self, [((NetGlobulusSimiSimiFunction *) nil_chk([candidate get])) bindWithNetGlobulusSimiSimiObjectImpl:(instance != nil) ? instance : self]);
  }
  if (self->superclasses_ != nil) {
    for (NetGlobulusSimiSimiClassImpl * __strong superclass_ in self->superclasses_) {
      NetGlobulusSimiSimiMethod *method = NetGlobulusSimiSimiClassImpl_findClosestVarargMethodWithNetGlobulusSimiSimiObjectImpl_withNSString_withInt_(nil_chk(superclass_), instance, name, arity);
      if (method != nil) {
        return method;
      }
    }
  }
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NetGlobulusSimiSimiClassImpl)

@implementation NetGlobulusSimiSimiClassImpl_SuperClassesList

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)value {
  NetGlobulusSimiSimiClassImpl_SuperClassesList_initWithJavaUtilList_(self, value);
  return self;
}

- (NetGlobulusSimiSimiValue *)copy__ {
  return new_NetGlobulusSimiSimiClassImpl_SuperClassesList_initWithJavaUtilList_(value_);
}

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_ {
  @throw new_JavaLangAssertionError_init();
}

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o {
  (void) cast_chk(o, [NetGlobulusSimiSimiValue class]);
  @throw new_JavaLangAssertionError_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiValue;", 0x1, 2, -1, -1, -1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiValue;", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 5, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithJavaUtilList:);
  methods[1].selector = @selector(copy__);
  methods[2].selector = @selector(cloneWithBoolean:);
  methods[3].selector = @selector(compareToWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "LJavaUtilList;", .constantValue.asLong = 0, 0x11, -1, -1, 7, -1 },
  };
  static const void *ptrTable[] = { "LJavaUtilList;", "(Ljava/util/List<LSimiClassImpl;>;)V", "copy", "clone", "Z", "compareTo", "LNetGlobulusSimiSimiValue;", "Ljava/util/List<LSimiClassImpl;>;", "LNetGlobulusSimiSimiClassImpl;" };
  static const J2ObjcClassInfo _NetGlobulusSimiSimiClassImpl_SuperClassesList = { "SuperClassesList", "net.globulus.simi", ptrTable, methods, fields, 7, 0x8, 4, 1, 8, -1, -1, -1, -1 };
  return &_NetGlobulusSimiSimiClassImpl_SuperClassesList;
}

@end

void NetGlobulusSimiSimiClassImpl_SuperClassesList_initWithJavaUtilList_(NetGlobulusSimiSimiClassImpl_SuperClassesList *self, id<JavaUtilList> value) {
  NetGlobulusSimiSimiValue_init(self);
  self->value_ = value;
}

NetGlobulusSimiSimiClassImpl_SuperClassesList *new_NetGlobulusSimiSimiClassImpl_SuperClassesList_initWithJavaUtilList_(id<JavaUtilList> value) {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_SuperClassesList, initWithJavaUtilList_, value)
}

NetGlobulusSimiSimiClassImpl_SuperClassesList *create_NetGlobulusSimiSimiClassImpl_SuperClassesList_initWithJavaUtilList_(id<JavaUtilList> value) {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_SuperClassesList, initWithJavaUtilList_, value)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NetGlobulusSimiSimiClassImpl_SuperClassesList)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$1

- (jboolean)testWithId:(id<JavaUtilMap_Entry>)e {
  return [((NSString *) nil_chk(((NetGlobulusSimiOverloadableFunction *) nil_chk([((id<JavaUtilMap_Entry>) nil_chk(e)) getKey]))->name_)) isEqual:val$name_];
}

- (id<JavaUtilFunctionPredicate>)and__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_and__WithJavaUtilFunctionPredicate_(self, arg0);
}

- (id<JavaUtilFunctionPredicate>)negate {
  return JavaUtilFunctionPredicate_negate(self);
}

- (id<JavaUtilFunctionPredicate>)or__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_or__WithJavaUtilFunctionPredicate_(self, arg0);
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(NetGlobulusSimiSimiClassImpl_$Lambda$1 *self, NSString *capture$0) {
  self->val$name_ = capture$0;
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$1 *new_NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(NSString *capture$0) {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$1, initWithNSString_, capture$0)
}

NetGlobulusSimiSimiClassImpl_$Lambda$1 *create_NetGlobulusSimiSimiClassImpl_$Lambda$1_initWithNSString_(NSString *capture$0) {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$1, initWithNSString_, capture$0)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$2)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$2

- (id)applyWithId:(id<JavaUtilMap_Entry>)a {
  return [((id<JavaUtilMap_Entry>) nil_chk(a)) getValue];
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$2 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$2_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$2_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$2)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$2_init(NetGlobulusSimiSimiClassImpl_$Lambda$2 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$2 *new_NetGlobulusSimiSimiClassImpl_$Lambda$2_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$2, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$2 *create_NetGlobulusSimiSimiClassImpl_$Lambda$2_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$2, init)
}

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$3

- (jboolean)testWithId:(id<JavaUtilMap_Entry>)e {
  return [((NSString *) nil_chk(((NetGlobulusSimiOverloadableFunction *) nil_chk([((id<JavaUtilMap_Entry>) nil_chk(e)) getKey]))->name_)) isEqual:val$name_] && ((NetGlobulusSimiOverloadableFunction *) nil_chk([e getKey]))->arity_ <= val$arity_;
}

- (id<JavaUtilFunctionPredicate>)and__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_and__WithJavaUtilFunctionPredicate_(self, arg0);
}

- (id<JavaUtilFunctionPredicate>)negate {
  return JavaUtilFunctionPredicate_negate(self);
}

- (id<JavaUtilFunctionPredicate>)or__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_or__WithJavaUtilFunctionPredicate_(self, arg0);
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(NetGlobulusSimiSimiClassImpl_$Lambda$3 *self, NSString *capture$0, jint capture$1) {
  self->val$name_ = capture$0;
  self->val$arity_ = capture$1;
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$3 *new_NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(NSString *capture$0, jint capture$1) {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$3, initWithNSString_withInt_, capture$0, capture$1)
}

NetGlobulusSimiSimiClassImpl_$Lambda$3 *create_NetGlobulusSimiSimiClassImpl_$Lambda$3_initWithNSString_withInt_(NSString *capture$0, jint capture$1) {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$3, initWithNSString_withInt_, capture$0, capture$1)
}

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$4

- (jint)applyAsIntWithId:(id<JavaUtilMap_Entry>)l {
  return JavaLangMath_absWithInt_(((NetGlobulusSimiOverloadableFunction *) nil_chk([((id<JavaUtilMap_Entry>) nil_chk(l)) getKey]))->arity_ - val$arity_);
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(NetGlobulusSimiSimiClassImpl_$Lambda$4 *self, jint capture$0) {
  self->val$arity_ = capture$0;
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$4 *new_NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(jint capture$0) {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$4, initWithInt_, capture$0)
}

NetGlobulusSimiSimiClassImpl_$Lambda$4 *create_NetGlobulusSimiSimiClassImpl_$Lambda$4_initWithInt_(jint capture$0) {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$4, initWithInt_, capture$0)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$5)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$5

- (id)applyWithId:(id<JavaUtilMap_Entry>)a {
  return [((id<JavaUtilMap_Entry>) nil_chk(a)) getValue];
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$5 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$5_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$5_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$5)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$5_init(NetGlobulusSimiSimiClassImpl_$Lambda$5 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$5 *new_NetGlobulusSimiSimiClassImpl_$Lambda$5_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$5, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$5 *create_NetGlobulusSimiSimiClassImpl_$Lambda$5_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$5, init)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$6)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$6

- (id)applyWithId:(NetGlobulusSimiSimiClassImpl *)c {
  return ((NetGlobulusSimiSimiClassImpl *) nil_chk(c))->name_;
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$6 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$6_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$6_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$6)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$6_init(NetGlobulusSimiSimiClassImpl_$Lambda$6 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$6 *new_NetGlobulusSimiSimiClassImpl_$Lambda$6_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$6, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$6 *create_NetGlobulusSimiSimiClassImpl_$Lambda$6_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$6, init)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$7)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$7

- (id)applyWithId:(NSString *)l
           withId:(NSString *)r {
  return JreStrcat("$$$", l, @", ", r);
}

- (id<JavaUtilFunctionBiFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionBiFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$7 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$7_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$7_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$7)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$7_init(NetGlobulusSimiSimiClassImpl_$Lambda$7 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$7 *new_NetGlobulusSimiSimiClassImpl_$Lambda$7_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$7, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$7 *create_NetGlobulusSimiSimiClassImpl_$Lambda$7_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$7, init)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$8)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$8

- (jboolean)testWithId:(id<JavaUtilMap_Entry>)e {
  return [((NSString *) nil_chk(((NetGlobulusSimiOverloadableFunction *) nil_chk([((id<JavaUtilMap_Entry>) nil_chk(e)) getKey]))->name_)) isEqual:NetGlobulusSimiConstants_INIT] || [((NetGlobulusSimiOverloadableFunction *) nil_chk([e getKey]))->name_ isEqual:JreStrcat("$$", NetGlobulusSimiConstants_PRIVATE, NetGlobulusSimiConstants_INIT)];
}

- (id<JavaUtilFunctionPredicate>)and__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_and__WithJavaUtilFunctionPredicate_(self, arg0);
}

- (id<JavaUtilFunctionPredicate>)negate {
  return JavaUtilFunctionPredicate_negate(self);
}

- (id<JavaUtilFunctionPredicate>)or__WithJavaUtilFunctionPredicate:(id<JavaUtilFunctionPredicate>)arg0 {
  return JavaUtilFunctionPredicate_or__WithJavaUtilFunctionPredicate_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$8 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$8_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$8_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$8)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$8_init(NetGlobulusSimiSimiClassImpl_$Lambda$8 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$8 *new_NetGlobulusSimiSimiClassImpl_$Lambda$8_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$8, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$8 *create_NetGlobulusSimiSimiClassImpl_$Lambda$8_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$8, init)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$9)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$9

- (id)applyWithId:(id<JavaUtilMap_Entry>)a {
  return [((id<JavaUtilMap_Entry>) nil_chk(a)) getValue];
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$9 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$9_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$9_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$9)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$9_init(NetGlobulusSimiSimiClassImpl_$Lambda$9 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$9 *new_NetGlobulusSimiSimiClassImpl_$Lambda$9_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$9, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$9 *create_NetGlobulusSimiSimiClassImpl_$Lambda$9_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$9, init)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$10)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$10

- (id)applyWithId:(NSString *)a {
  return new_NetGlobulusSimiSimiValue_String_initWithNSString_(a);
}

- (id<JavaUtilFunctionFunction>)composeWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_composeWithJavaUtilFunctionFunction_(self, arg0);
}

- (id<JavaUtilFunctionFunction>)andThenWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)arg0 {
  return JavaUtilFunctionFunction_andThenWithJavaUtilFunctionFunction_(self, arg0);
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$10 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$10_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$10_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$10)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$10_init(NetGlobulusSimiSimiClassImpl_$Lambda$10 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$10 *new_NetGlobulusSimiSimiClassImpl_$Lambda$10_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$10, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$10 *create_NetGlobulusSimiSimiClassImpl_$Lambda$10_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$10, init)
}

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiSimiClassImpl_$Lambda$11)

@implementation NetGlobulusSimiSimiClassImpl_$Lambda$11

- (id)get {
  return new_JavaUtilArrayList_init();
}

+ (void)initialize {
  if (self == [NetGlobulusSimiSimiClassImpl_$Lambda$11 class]) {
    NetGlobulusSimiSimiClassImpl_$Lambda$11_instance = new_NetGlobulusSimiSimiClassImpl_$Lambda$11_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiSimiClassImpl_$Lambda$11)
  }
}

@end

void NetGlobulusSimiSimiClassImpl_$Lambda$11_init(NetGlobulusSimiSimiClassImpl_$Lambda$11 *self) {
  NSObject_init(self);
}

NetGlobulusSimiSimiClassImpl_$Lambda$11 *new_NetGlobulusSimiSimiClassImpl_$Lambda$11_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$11, init)
}

NetGlobulusSimiSimiClassImpl_$Lambda$11 *create_NetGlobulusSimiSimiClassImpl_$Lambda$11_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiSimiClassImpl_$Lambda$11, init)
}
