//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/SimiValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiSimiValue")
#ifdef RESTRICT_NetGlobulusSimiSimiValue
#define INCLUDE_ALL_NetGlobulusSimiSimiValue 0
#else
#define INCLUDE_ALL_NetGlobulusSimiSimiValue 1
#endif
#undef RESTRICT_NetGlobulusSimiSimiValue
#ifdef INCLUDE_NetGlobulusSimiSimiValue_Callable
#define INCLUDE_NetGlobulusSimiSimiValue 1
#endif
#ifdef INCLUDE_NetGlobulusSimiSimiValue_Object
#define INCLUDE_NetGlobulusSimiSimiValue 1
#endif
#ifdef INCLUDE_NetGlobulusSimiSimiValue_Number
#define INCLUDE_NetGlobulusSimiSimiValue 1
#endif
#ifdef INCLUDE_NetGlobulusSimiSimiValue_String
#define INCLUDE_NetGlobulusSimiSimiValue 1
#endif

#if !defined (NetGlobulusSimiSimiValue_) && (INCLUDE_ALL_NetGlobulusSimiSimiValue || defined(INCLUDE_NetGlobulusSimiSimiValue))
#define NetGlobulusSimiSimiValue_

#define RESTRICT_NetGlobulusSimiSimiProperty 1
#define INCLUDE_NetGlobulusSimiSimiProperty 1
#include "SimiProperty.h"

#define RESTRICT_JavaLangComparable 1
#define INCLUDE_JavaLangComparable 1
#include "java/lang/Comparable.h"

@class JavaLangDouble;
@protocol JavaUtilList;
@protocol NetGlobulusSimiSimiCallable;
@protocol NetGlobulusSimiSimiObject;

@interface NetGlobulusSimiSimiValue : NSObject < NetGlobulusSimiSimiProperty, JavaLangComparable >

#pragma mark Public

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (id<JavaUtilList>)getAnnotations;

- (id<NetGlobulusSimiSimiCallable>)getCallable;

- (JavaLangDouble *)getNumber;

- (id<NetGlobulusSimiSimiObject>)getObject;

- (NSString *)getString;

- (NetGlobulusSimiSimiValue *)getValue;

- (void)setValueWithNetGlobulusSimiSimiValue:(NetGlobulusSimiSimiValue *)value;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiValue)

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_init(NetGlobulusSimiSimiValue *self);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiValue)

#endif

#if !defined (NetGlobulusSimiSimiValue_String_) && (INCLUDE_ALL_NetGlobulusSimiSimiValue || defined(INCLUDE_NetGlobulusSimiSimiValue_String))
#define NetGlobulusSimiSimiValue_String_

@class NetGlobulusSimiSimiValue;

@interface NetGlobulusSimiSimiValue_String : NetGlobulusSimiSimiValue {
 @public
  NSString *value_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)value;

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isEqual:(id)obj;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiValue_String)

J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiValue_String, value_, NSString *)

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_String_initWithNSString_(NetGlobulusSimiSimiValue_String *self, NSString *value);

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_String *new_NetGlobulusSimiSimiValue_String_initWithNSString_(NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_String *create_NetGlobulusSimiSimiValue_String_initWithNSString_(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiValue_String)

#endif

#if !defined (NetGlobulusSimiSimiValue_Number_) && (INCLUDE_ALL_NetGlobulusSimiSimiValue || defined(INCLUDE_NetGlobulusSimiSimiValue_Number))
#define NetGlobulusSimiSimiValue_Number_

@class NetGlobulusSimiSimiValue;

@interface NetGlobulusSimiSimiValue_Number : NetGlobulusSimiSimiValue {
 @public
  jdouble value_;
}

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)value;

- (instancetype)initWithDouble:(jdouble)value;

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isEqual:(id)obj;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiSimiValue_Number)

inline NetGlobulusSimiSimiValue_Number *NetGlobulusSimiSimiValue_Number_get_TRUE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Number *NetGlobulusSimiSimiValue_Number_TRUE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiValue_Number, TRUE, NetGlobulusSimiSimiValue_Number *)

inline NetGlobulusSimiSimiValue_Number *NetGlobulusSimiSimiValue_Number_get_FALSE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Number *NetGlobulusSimiSimiValue_Number_FALSE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiSimiValue_Number, FALSE, NetGlobulusSimiSimiValue_Number *)

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_Number_initWithDouble_(NetGlobulusSimiSimiValue_Number *self, jdouble value);

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Number *new_NetGlobulusSimiSimiValue_Number_initWithDouble_(jdouble value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Number *create_NetGlobulusSimiSimiValue_Number_initWithDouble_(jdouble value);

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_Number_initWithBoolean_(NetGlobulusSimiSimiValue_Number *self, jboolean value);

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Number *new_NetGlobulusSimiSimiValue_Number_initWithBoolean_(jboolean value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Number *create_NetGlobulusSimiSimiValue_Number_initWithBoolean_(jboolean value);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiValue_Number)

#endif

#if !defined (NetGlobulusSimiSimiValue_Object_) && (INCLUDE_ALL_NetGlobulusSimiSimiValue || defined(INCLUDE_NetGlobulusSimiSimiValue_Object))
#define NetGlobulusSimiSimiValue_Object_

@class NetGlobulusSimiSimiValue;
@protocol NetGlobulusSimiSimiObject;

@interface NetGlobulusSimiSimiValue_Object : NetGlobulusSimiSimiValue {
 @public
  id<NetGlobulusSimiSimiObject> value_;
}

#pragma mark Public

- (instancetype)initWithNetGlobulusSimiSimiObject:(id<NetGlobulusSimiSimiObject>)value;

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isEqual:(id)obj;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiValue_Object)

J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiValue_Object, value_, id<NetGlobulusSimiSimiObject>)

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_Object_initWithNetGlobulusSimiSimiObject_(NetGlobulusSimiSimiValue_Object *self, id<NetGlobulusSimiSimiObject> value);

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Object *new_NetGlobulusSimiSimiValue_Object_initWithNetGlobulusSimiSimiObject_(id<NetGlobulusSimiSimiObject> value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Object *create_NetGlobulusSimiSimiValue_Object_initWithNetGlobulusSimiSimiObject_(id<NetGlobulusSimiSimiObject> value);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiValue_Object)

#endif

#if !defined (NetGlobulusSimiSimiValue_Callable_) && (INCLUDE_ALL_NetGlobulusSimiSimiValue || defined(INCLUDE_NetGlobulusSimiSimiValue_Callable))
#define NetGlobulusSimiSimiValue_Callable_

@class NetGlobulusSimiSimiValue;
@protocol NetGlobulusSimiSimiCallable;
@protocol NetGlobulusSimiSimiObject;

@interface NetGlobulusSimiSimiValue_Callable : NetGlobulusSimiSimiValue {
 @public
  id<NetGlobulusSimiSimiCallable> value_;
  NSString *name_;
}

#pragma mark Public

- (instancetype)initWithNetGlobulusSimiSimiCallable:(id<NetGlobulusSimiSimiCallable>)value
                                       withNSString:(NSString *)name
                      withNetGlobulusSimiSimiObject:(id<NetGlobulusSimiSimiObject>)instance;

- (void)bindWithNetGlobulusSimiSimiObject:(id<NetGlobulusSimiSimiObject>)instance;

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isEqual:(id)obj;

- (id<NetGlobulusSimiSimiObject>)getInstance;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiValue_Callable)

J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiValue_Callable, value_, id<NetGlobulusSimiSimiCallable>)
J2OBJC_FIELD_SETTER(NetGlobulusSimiSimiValue_Callable, name_, NSString *)

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_Callable_initWithNetGlobulusSimiSimiCallable_withNSString_withNetGlobulusSimiSimiObject_(NetGlobulusSimiSimiValue_Callable *self, id<NetGlobulusSimiSimiCallable> value, NSString *name, id<NetGlobulusSimiSimiObject> instance);

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Callable *new_NetGlobulusSimiSimiValue_Callable_initWithNetGlobulusSimiSimiCallable_withNSString_withNetGlobulusSimiSimiObject_(id<NetGlobulusSimiSimiCallable> value, NSString *name, id<NetGlobulusSimiSimiObject> instance) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_Callable *create_NetGlobulusSimiSimiValue_Callable_initWithNetGlobulusSimiSimiCallable_withNSString_withNetGlobulusSimiSimiObject_(id<NetGlobulusSimiSimiCallable> value, NSString *name, id<NetGlobulusSimiSimiObject> instance);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiValue_Callable)

#endif

#if !defined (NetGlobulusSimiSimiValue_IncompatibleValuesException_) && (INCLUDE_ALL_NetGlobulusSimiSimiValue || defined(INCLUDE_NetGlobulusSimiSimiValue_IncompatibleValuesException))
#define NetGlobulusSimiSimiValue_IncompatibleValuesException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class IOSClass;
@class JavaLangThrowable;

@interface NetGlobulusSimiSimiValue_IncompatibleValuesException : JavaLangRuntimeException

#pragma mark Package-Private

- (instancetype)initWithIOSClass:(IOSClass *)value
                    withIOSClass:(IOSClass *)expected;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiValue_IncompatibleValuesException)

FOUNDATION_EXPORT void NetGlobulusSimiSimiValue_IncompatibleValuesException_initWithIOSClass_withIOSClass_(NetGlobulusSimiSimiValue_IncompatibleValuesException *self, IOSClass *value, IOSClass *expected);

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_IncompatibleValuesException *new_NetGlobulusSimiSimiValue_IncompatibleValuesException_initWithIOSClass_withIOSClass_(IOSClass *value, IOSClass *expected) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiValue_IncompatibleValuesException *create_NetGlobulusSimiSimiValue_IncompatibleValuesException_initWithIOSClass_withIOSClass_(IOSClass *value, IOSClass *expected);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiValue_IncompatibleValuesException)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiSimiValue")
