//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/SimiException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiSimiException")
#ifdef RESTRICT_NetGlobulusSimiSimiException
#define INCLUDE_ALL_NetGlobulusSimiSimiException 0
#else
#define INCLUDE_ALL_NetGlobulusSimiSimiException 1
#endif
#undef RESTRICT_NetGlobulusSimiSimiException

#if !defined (NetGlobulusSimiSimiException_) && (INCLUDE_ALL_NetGlobulusSimiSimiException || defined(INCLUDE_NetGlobulusSimiSimiException))
#define NetGlobulusSimiSimiException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

#define RESTRICT_NetGlobulusSimiSimiObject 1
#define INCLUDE_NetGlobulusSimiSimiObject 1
#include "SimiObject.h"

@class JavaLangThrowable;
@protocol JavaUtilList;
@protocol NetGlobulusSimiSimiClass;
@protocol NetGlobulusSimiSimiEnvironment;
@protocol NetGlobulusSimiSimiProperty;

@interface NetGlobulusSimiSimiException : JavaLangRuntimeException < NetGlobulusSimiSimiObject >

#pragma mark Public

- (instancetype)initWithNetGlobulusSimiSimiClass:(id<NetGlobulusSimiSimiClass>)clazz
                                    withNSString:(NSString *)message;

- (id<NetGlobulusSimiSimiObject>)cloneWithBoolean:(jboolean)mutable_;

- (id<NetGlobulusSimiSimiProperty>)getWithNSString:(NSString *)key
                withNetGlobulusSimiSimiEnvironment:(id<NetGlobulusSimiSimiEnvironment>)environment;

- (id<NetGlobulusSimiSimiClass>)getSimiClass;

- (void)setWithNSString:(NSString *)key
withNetGlobulusSimiSimiProperty:(id<NetGlobulusSimiSimiProperty>)value
withNetGlobulusSimiSimiEnvironment:(id<NetGlobulusSimiSimiEnvironment>)environment;

- (id<JavaUtilList>)values;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetGlobulusSimiSimiException)

FOUNDATION_EXPORT void NetGlobulusSimiSimiException_initWithNetGlobulusSimiSimiClass_withNSString_(NetGlobulusSimiSimiException *self, id<NetGlobulusSimiSimiClass> clazz, NSString *message);

FOUNDATION_EXPORT NetGlobulusSimiSimiException *new_NetGlobulusSimiSimiException_initWithNetGlobulusSimiSimiClass_withNSString_(id<NetGlobulusSimiSimiClass> clazz, NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetGlobulusSimiSimiException *create_NetGlobulusSimiSimiException_initWithNetGlobulusSimiSimiClass_withNSString_(id<NetGlobulusSimiSimiClass> clazz, NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiSimiException)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiSimiException")
