//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/TempNull.java
//

#include "J2ObjC_source.h"
#include "SimiValue.h"
#include "TempNull.h"

@interface NetGlobulusSimiTempNull ()

- (instancetype)init;

@end

__attribute__((unused)) static void NetGlobulusSimiTempNull_init(NetGlobulusSimiTempNull *self);

__attribute__((unused)) static NetGlobulusSimiTempNull *new_NetGlobulusSimiTempNull_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static NetGlobulusSimiTempNull *create_NetGlobulusSimiTempNull_init(void);

J2OBJC_INITIALIZED_DEFN(NetGlobulusSimiTempNull)

NetGlobulusSimiTempNull *NetGlobulusSimiTempNull_INSTANCE;

@implementation NetGlobulusSimiTempNull

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  NetGlobulusSimiTempNull_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NetGlobulusSimiSimiValue *)copy__ {
  return self;
}

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_ {
  return self;
}

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o {
  (void) cast_chk(o, [NetGlobulusSimiSimiValue class]);
  return 0;
}

- (NSString *)description {
  return @"nil";
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiValue;", 0x1, 0, -1, -1, -1, -1, -1 },
    { NULL, "LNetGlobulusSimiSimiValue;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 5, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(copy__);
  methods[2].selector = @selector(cloneWithBoolean:);
  methods[3].selector = @selector(compareToWithId:);
  methods[4].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INSTANCE", "LNetGlobulusSimiTempNull;", .constantValue.asLong = 0, 0x18, -1, 6, -1, -1 },
  };
  static const void *ptrTable[] = { "copy", "clone", "Z", "compareTo", "LNetGlobulusSimiSimiValue;", "toString", &NetGlobulusSimiTempNull_INSTANCE };
  static const J2ObjcClassInfo _NetGlobulusSimiTempNull = { "TempNull", "net.globulus.simi", ptrTable, methods, fields, 7, 0x0, 5, 1, -1, -1, -1, -1, -1 };
  return &_NetGlobulusSimiTempNull;
}

+ (void)initialize {
  if (self == [NetGlobulusSimiTempNull class]) {
    NetGlobulusSimiTempNull_INSTANCE = new_NetGlobulusSimiTempNull_init();
    J2OBJC_SET_INITIALIZED(NetGlobulusSimiTempNull)
  }
}

@end

void NetGlobulusSimiTempNull_init(NetGlobulusSimiTempNull *self) {
  NetGlobulusSimiSimiValue_init(self);
}

NetGlobulusSimiTempNull *new_NetGlobulusSimiTempNull_init() {
  J2OBJC_NEW_IMPL(NetGlobulusSimiTempNull, init)
}

NetGlobulusSimiTempNull *create_NetGlobulusSimiTempNull_init() {
  J2OBJC_CREATE_IMPL(NetGlobulusSimiTempNull, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NetGlobulusSimiTempNull)
