//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/TempNull.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiTempNull")
#ifdef RESTRICT_NetGlobulusSimiTempNull
#define INCLUDE_ALL_NetGlobulusSimiTempNull 0
#else
#define INCLUDE_ALL_NetGlobulusSimiTempNull 1
#endif
#undef RESTRICT_NetGlobulusSimiTempNull

#if !defined (NetGlobulusSimiTempNull_) && (INCLUDE_ALL_NetGlobulusSimiTempNull || defined(INCLUDE_NetGlobulusSimiTempNull))
#define NetGlobulusSimiTempNull_

#define RESTRICT_NetGlobulusSimiSimiValue 1
#define INCLUDE_NetGlobulusSimiSimiValue 1
#include "SimiValue.h"

@interface NetGlobulusSimiTempNull : NetGlobulusSimiSimiValue

#pragma mark Public

- (NetGlobulusSimiSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(NetGlobulusSimiSimiValue *)o;

- (NetGlobulusSimiSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(NetGlobulusSimiTempNull)

inline NetGlobulusSimiTempNull *NetGlobulusSimiTempNull_get_INSTANCE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NetGlobulusSimiTempNull *NetGlobulusSimiTempNull_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetGlobulusSimiTempNull, INSTANCE, NetGlobulusSimiTempNull *)

J2OBJC_TYPE_LITERAL_HEADER(NetGlobulusSimiTempNull)

#endif

#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiTempNull")
