//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/TempNull.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiTempNull")
#ifdef RESTRICT_NetGlobulusSimiTempNull
#define INCLUDE_ALL_NetGlobulusSimiTempNull 0
#else
#define INCLUDE_ALL_NetGlobulusSimiTempNull 1
#endif
#undef RESTRICT_NetGlobulusSimiTempNull

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SMTempNull_) && (INCLUDE_ALL_NetGlobulusSimiTempNull || defined(INCLUDE_SMTempNull))
#define SMTempNull_

#define RESTRICT_NetGlobulusSimiSimiValue 1
#define INCLUDE_SMSimiValue 1
#include "SimiValue.h"

@interface SMTempNull : SMSimiValue

+ (SMTempNull *)INSTANCE;

#pragma mark Public

- (SMSimiValue *)cloneWithBoolean:(jboolean)mutable_;

- (jint)compareToWithId:(SMSimiValue *)o;

- (SMSimiValue *)copy__ OBJC_METHOD_FAMILY_NONE;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(SMTempNull)

inline SMTempNull *SMTempNull_get_INSTANCE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT SMTempNull *SMTempNull_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SMTempNull, INSTANCE, SMTempNull *)

J2OBJC_TYPE_LITERAL_HEADER(SMTempNull)

@compatibility_alias NetGlobulusSimiTempNull SMTempNull;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiTempNull")
