//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/Yield.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetGlobulusSimiYield")
#ifdef RESTRICT_NetGlobulusSimiYield
#define INCLUDE_ALL_NetGlobulusSimiYield 0
#else
#define INCLUDE_ALL_NetGlobulusSimiYield 1
#endif
#undef RESTRICT_NetGlobulusSimiYield

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SMYield_) && (INCLUDE_ALL_NetGlobulusSimiYield || defined(INCLUDE_SMYield))
#define SMYield_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;
@protocol SMSimiProperty;

@interface SMYield : JavaLangRuntimeException {
 @public
  id<SMSimiProperty> prop_;
  jboolean rethrown_;
}

#pragma mark Package-Private

- (instancetype __nonnull)initWithSMSimiProperty:(id<SMSimiProperty>)prop
                                     withBoolean:(jboolean)rethrown;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1
                               withBoolean:(jboolean)arg2
                               withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SMYield)

J2OBJC_FIELD_SETTER(SMYield, prop_, id<SMSimiProperty>)

FOUNDATION_EXPORT void SMYield_initWithSMSimiProperty_withBoolean_(SMYield *self, id<SMSimiProperty> prop, jboolean rethrown);

FOUNDATION_EXPORT SMYield *new_SMYield_initWithSMSimiProperty_withBoolean_(id<SMSimiProperty> prop, jboolean rethrown) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SMYield *create_SMYield_initWithSMSimiProperty_withBoolean_(id<SMSimiProperty> prop, jboolean rethrown);

J2OBJC_TYPE_LITERAL_HEADER(SMYield)

@compatibility_alias NetGlobulusSimiYield SMYield;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetGlobulusSimiYield")
